name: GitHub Actions Demo
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      # report machine parameters
      - run: npx cypress info
      - run: node -p 'os.cpus()'

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: dist
          if-no-files-found: error
          path: dist
